### ISSUE TITLE
request timeout on sending

### ISSUE THREAD

**Issue by HaythamTantoush** [iref-use/ps4-remote-pkg-sender#10]
i tried both the package installers (flatz and opoo)
they connect and both the ps4 and the local servers are a go
but when i press the play button to start installing the game it sets for a couble of seconds then spits out the request timeout
tried every troubleshooting step nothing worked

**Comment by Gkiokan** [comment]
Have a look into the [Troubleshooting Guide](https://github.com/Gkiokan/ps4-remote-pkg-sender/blob/master/Troubleshoot.md#i-get-timeout-error). It is also accessible though the miscs Menu on the app (v2).

**Comment by fakusnamus** [comment]
I have the same issue, and the troubleshooting guide didn't help. RPI was open on the PS4 and the correct IP address was entered, with the PS4 connected successfully via LAN.

**Comment by Gkiokan** [comment]
Open the `PS4 API Logs` and check what it says. 
If there are no further detailed information try to restart your ps4 and test the connection again.  
Usually if you make a connection test and it says sucessfully connected you can send packages to it.  
 
However if you still have trouble, check if you can ping your PS4 on the terminal.  
If that does work but the Sender doesn't it may be a security issue that something blocks the connection from the sender.  

<img width="280" alt="image" src="https://user-images.githubusercontent.com/7249224/175785882-b5662c77-6455-4305-a3f6-29a90b3ee1d8.png">
