### ISSUE TITLE
How to force install when game already installed

### ISSUE THREAD

**Issue by wankio** [iref-use/ps4-remote-pkg-sender#12]
Some game broken or install mod, so i need copy it into USB/extHDD and install with debug setting. 

ps4 remote pkg sender wont let me force install when game already installed.

**Comment by Gkiokan** [comment]
Just delete all occurences from the game in your Bibliothek and Notifications.  
Also check any download status from a game. Delete everything you can find and try again.  
  
Currently there is no uninstall option from the RPI itself. So we can't trigger uninstalling a game. But there may be some options in v2.9-2.10 in the next features lists with the integrated FTP client.
