### ISSUE TITLE
Fpkg stops and cannot be downloaded 

### ISSUE THREAD

**Issue by JNKD0G** [iref-use/ps4-remote-pkg-sender#15]
![IMG_20230314_232827](https://user-images.githubusercontent.com/120760361/225156488-471aabb0-937d-46f5-814c-09eebfc51185.jpg)

The progress just stops at a certain point. This happens only with large pkgs (larger than 10gb). I've tried different pkg senders and different fpkgs (games) and even changed the dns. I'm at the point of losing my mind. Thank you for your work

**Comment by Gkiokan** [comment]
Check out Sam Daniels Video first [https://www.youtube.com/watch?v=RyKUm5rndPQ&t=36s](https://www.youtube.com/watch?v=RyKUm5rndPQ&t=36s).  
Even the video is for an older version, the basic and setup for connection etc. still applies.  

Actually if it starts Installing on your ps4 it should continue, even if you don't get any updates anymore.   Just by looking at your rest timer it seems that you are connected with WiFi. There is a bunch of speed optimization on your side.
