### ISSUE TITLE
Error 2157510677 | It seems to be installed already

### ISSUE THREAD

**Issue by MarloGrayhat** [iref-use/ps4-remote-pkg-sender#17]
I tried to install as usual the game, but something went wrong and the download stopped, somewhere around 70%. I exited Remote PKG Installer to check the network status, because the download was at 70% for more than 10 minutes, although the internet speed is very fast at home and both devices are not far from the routers, when I went back to Remote PKG Installer and waited some more time nothing changed. I canceled the download via Remote pkg sender and rebooted the ps4. Since then when I try to install the app again I get "Error 2157510677 | It seems to be installed already". Now I have looked at all the files in ps4 that I can through "PS4 Xplorer" and deleted everything related to this game, including opening json, however, I can not install the game, I get the same error 2157510677. 

Please, help me)

**Comment by Gkiokan** [comment]
Already solved https://github.com/Gkiokan/ps4-remote-pkg-sender/issues/63

**Comment by pan-goofy** [comment]
我也遇到了同样的问题，我删除缓存重启ps4都没有解决，最后判断是ps4的问题，在最新资讯中删掉了失败的记录后,可以安装游戏了
