### ISSUE TITLE
pkg tasks stuck in app but downloading in ps4

### ISSUE THREAD

**Issue by farhmadi** [iref-use/ps4-remote-pkg-sender#18]
hi, there is an issue that progress stucks on second pkg at some point after installing the first pkg (some times stucks on third pkg, i think it stucks at certain passed time liked 30min), but game is downloading in ps4 and installs perfectly fine. stucking stops the queue and i have to reset finished and remove the stuck one, then reopen rpi and hit autostart again. i have 2 pcs and i tried on both, what the problem? can u help me

My Setup:
- PS4.Remote.PKG.Sender.V2-2.10.3
- NodeJS 14.15.3
- Lan Setup (Based on Tutorial By Sam Daniel | [Link](https://www.youtube.com/watch?v=RyKUm5rndPQ))
- and i tried WIFI Shared on Ethernet too (Same issue)
- 3 diffrent modems (same issue)

by the way before this app i was using [FrostySo](https://github.com/FrostySo)'s PS4 PKG Sender and why im mentioning this is because on the first run there was a popup to install http-server. i thought this info will be helpful to help me

and thank you for the awesome work

**Comment by Gkiokan** [comment]
Unfortunatelly this is still a issue with the RPI on Playstation.  
Described here in the Troubleshooting Guide: 
https://github.com/Gkiokan/ps4-remote-pkg-sender/blob/master/Troubleshoot.md#my-rpi-crashes-on-console

But there will hopefully some embeded integrated feature with Sistros GoldHEN soon.
