### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by saijayaprakash** [iref-use/ps4-remote-pkg-sender#2]
After clicking Send button got disabled and no logs got printed it just stood dumb

**Comment by bushnerd** [comment]
I also have this issue.

**Comment by nodifference** [comment]
Same the test of server in browser is ok but no logs

**Comment by Gkiokan** [comment]
Probably restart the tool once. 

-- notice

This repository will be updated to the latest stable releases of the v2.  

You can follow the latest updates along the forked repo [here](https://github.com/Gkiokan/ps4-remote-pkg-sender) and checkout the [latest releases here](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/latest).
However if you wish to use the legacy v1 you can check the [v1 releases here](https://github.com/iref-use/ps4-remote-pkg-sender/releases) (no further development).
