### ISSUE TITLE
feature: headless version

### ISSUE THREAD

**Issue by GottZ** [iref-use/ps4-remote-pkg-sender#20]
as someone running a home server without desktop, I'd like to use this headless without X11

(just leaving this here as reference in case I actually free this tool from GUI somewhere down my to-do list)

**Comment by Gkiokan** [comment]
@iref-use Could you add me as collaborator on your repo, as ppl mistakenly coming here and I can't operate the Issues or lates Merges. 

@GottZ https://github.com/Gkiokan/ps4-remote-pkg-sender/issues/66#issuecomment-2131146061

**Comment by GottZ** [comment]
closing it as dupe

**Comment by iref-use** [comment]
> @iref-use Could you add me as collaborator on your repo, as ppl mistakenly coming here and I can't operate the Issues or lates Merges.
> 
> @GottZ [Gkiokan#66 (comment)](https://github.com/Gkiokan/ps4-remote-pkg-sender/issues/66#issuecomment-2131146061)

Done.

**Comment by Gkiokan** [comment]
> > @iref-use Could you add me as collaborator on your repo, as ppl mistakenly coming here and I can't operate the Issues or lates Merges.
> > @GottZ [Gkiokan#66 (comment)](https://github.com/Gkiokan/ps4-remote-pkg-sender/issues/66#issuecomment-2131146061)
> 
> Done.

Thanks mate. I will take care of the repos. 
Meanwhile can you get in touch with me over TG, Discord, Twitter, Face, insta, TikTok whatever fits you?
Can't find any contact information about you.
