### ISSUE TITLE
[Tech question] How does the trigger call look like?

### ISSUE THREAD

**Issue by g0r3** [iref-use/ps4-remote-pkg-sender#22]
Hi!

your tool has become my goto solution for shoveling games over onto my PS5. I am thinking about creating something similar for my particular needs, and I was reading some of your code to see how it works. Unfortunately I am not good with JS. I can see that the console fetches the PKG using a get request against the server created by this application. But what I could not find out is how this request is being triggered when clicking the play button on the UI of the app. Would you be so kind to explain that that to an ignorant?

Thank you very much!

**Comment by Gkiokan** [comment]
Hey!

Thanks for loving the App :)  Mentioning that you are on the ire-fuses repo which just gets the merged pull request to stay up2date. You may have opened this particular issue on the v2 repo - but doesn't matter. #21 

For the PS5 Install Requests checkout LM's description about the Request Endpoint [here](https://github.com/LightningMods/etaHEN?tab=readme-ov-file#dpi-api-details-for-tool-creators)

This is straight from his readme: 
```
etaHEN's Direct PKG Installer currently is very simple and is considered a WIP the service flow is as follows

Connect to etaHEN's TCP server via port 9090 (using the PS5s IP)
Send a URL to etaHEN in the following json format
{ "url" : "http://xxxx" }
etaHEN will then send back the return value (0 on success)
{ "res" : "0" }
etaHEN will close the client socket after the return json is sent
```

The files must be served via a Web Server to be able to be fetched on the PS4/5, thats the only reason why I scan the files and put them in my Server list. The triggering is done on my api modules, seperated for each plugin type (ps4, ps5, etahen, etc.)


For the PS4 there are post requests to the RPI of flatZ on the PS4 accordingly. Checkout the API Window for more information inside the App.  

Feel free to ask any open questions. Also get in touch with me over Discord or TG if you want. YW & HF
