### ISSUE TITLE
Latest Windows 10 version requires Windows 8 compatibilty mode

### ISSUE THREAD

**Issue by Buzbee** [iref-use/ps4-remote-pkg-sender#3]
20H1 Windows 10 Enterprise X64 : when opened up program stays all grey (never turns white). Program is still usable but you can no longer check on status/log window. Choosing an earlier Windows compatibility mode fixes the issues. Not sure what Win 10 version this started in as I had not used the program in a while.

**Comment by Gkiokan** [comment]
This repository will be updated to the latest stable releases of the v2.  

You can follow the latest updates along the forked repo [here](https://github.com/Gkiokan/ps4-remote-pkg-sender) and checkout the [latest releases here](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/latest).
However if you wish to use the legacy v1 you can check the [v1 releases here](https://github.com/iref-use/ps4-remote-pkg-sender/releases) (no further development).
