### ISSUE TITLE
why you not update your work

### ISSUE THREAD

**Issue by Constantine-HD** [iref-use/ps4-remote-pkg-sender#4]
your work and tools is the best program for sending pkg to ps4...but i do not know why you dont update it ..add such things like bach pkg send or staus bar or multi console pkg sender !!!!

**Comment by iref-use** [comment]
I am already working on an update. All the features except multi console send will be in this update with the updated GUI.

**Comment by wankio** [comment]
i'm noticed, if you transfer update file, it will not install yet, you must manual install it from notifications

**Comment by C0nsp1racy** [comment]
Nice! Looking forward to an updated, refreshed sender! 
I guess multi console send is broken and no way to fix it? (the other senders only use 1 stream a time)

**Comment by seisdr** [comment]
What if i dont want to use torrent link

**Comment by Gkiokan** [comment]
Hi folks,

this Project is continued by me and I call it the Remote Package Version 2.  
You can follow the latest updates along the forked repo [here](https://github.com/Gkiokan/ps4-remote-pkg-sender) and checkout the [latest releases here](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/latest)

This repository will be updated to the latest stable releases of the v2.  
However if you wish to use the legacy v1 you can check the [v1 releases here](https://github.com/iref-use/ps4-remote-pkg-sender/releases).

The legacy Version will not be continued as the v2 is already mainly maintained by me and gets further improvements.

Thanks.

**Comment by jonibim** [comment]
@Gkiokan Has this feature been already worked on? Otherwise I can have a look to at least add an Add all/Remove All button.
