### ISSUE TITLE
Flathub

### ISSUE THREAD

**Issue by iMonZ** [iref-use/ps4-remote-pkg-sender#9]
Hey,

could you publish your tool on Flathub?
Otherwise I could do that with your permission

**Comment by Gkiokan** [comment]
@iMonZ irefuse is kinda not active anymore on the main repo. Open the Issue on my [repo ](https://github.com/Gkiokan/ps4-remote-pkg-sender) which I actively maintain and I will give a look into it.

brew is also on my todo list.

**Comment by Gkiokan** [comment]
@iMonZ The applyment looks complicated at first glance, but feel free to add the latest stable release to it if you want. 
As I am myself not into linux, I cannot test the process for flathub, but I will add brew for sure. 

You can use the [Remote Package Sender v2 (v2.7.2-RC)](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.7.2) for flathub.  
This version will stay now for a long time until I apply new features.   

If you want to add the legacy version from irefuse you can add [Remote Package Sender v1.0.3](https://github.com/iref-use/ps4-remote-pkg-sender/releases/tag/v1.0.3)
